- name: redis provisioning
  hosts: redis
  become: yes
  vars:
    ansible_user: ec2-user
    ansible_password: DevOps321  
  tasks:
  - name: disable default redis module
    ansible.builtin.command: dnf module disable redis -y

  - name: enable redis module 7
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: Install redis 
    ansible.builtin.dnf:
      name: redis
      state: present

  - name: allow remote connections to server
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: remove protected mode 
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      search_string: 'protected-mode'
      line: protected-mode no